version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
    networks:
      - web
  php:
    build: ./php
    volumes:
      - ./code:/code
    environment:
      DB_HOST: db
      DB_DATABASE: docavel
      DB_USERNAME: admin
      DB_PASSWORD: secret
    networks:
      - web
      - database
  db:
    image: mariadb
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: docavel
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    networks:
      - database

networks:
  web:
    driver: bridge
  database:
    driver: bridge
